### ISSUE TITLE
Header elements unable to fill entire width

### ISSUE THREAD

**Issue by joshuanianji** [PaackEng/elm-ui-dialog#1]
Hello,

In [this simple Ellie](https://ellie-app.com/9mn3x2fGLZta1) I have a header element that I want to make the width of the screen, but it is confined to a small space on the left. I use `Element.paragraph` because it might have to wrap the text if the popup gets too small. 

I believe the problem lies with the `el [ alignLeft ] <| Maybe.withDefault none header` on [line 92](https://github.com/PaackEng/elm-ui-dialog/blob/1.0.0/src/Dialog.elm#L92) of the Dialog.elm. 

Would you mind adding a `width fill` attribute to the `el`? Thank you!

**Comment by miguelcoba** [comment]
Sorry for the delay @joshuanianji. Your proposed fix is merged to master. Thanks for reporting it.
